### ISSUE TITLE
[QE V5 Beta 10.5] DLL load failed while importing _cext

### ISSUE THREAD

**Issue by Tbolt10033** [ApatheticDELL/QuantumENDEC#10]
**Describe the bug**
What's the bug? Try to explain as much as possible so we can have as much information about it.
Error when trying to start QuantumEndec V5 Beta 10.5, 
**Expected behavior**
It is expected that QE will start up normally with all the installed modules.
**Unexpected behavior**
Steps to reproduce the problem:
Start up QE. (It may need to be a fresh build to reproduce error) it should say in the debug prints that it is missing or that it could not find a module it is looking for.

**Screenshots**
![Screenshot_2024-11-17_200449-2](https://github.com/user-attachments/assets/499f61c9-d05b-4819-bab2-1fde6abe4a14)

**Operating System & Python Version**
 - OS: Windows 11 24H2 with Python 3.12.5

**Additional context**
Debug says ImportError: DLL load failed while importing _cext: The specified module could not be found

**Comment by ApatheticDELL** [comment]
Did you install python via Microsoft Store or downloaded installer (exe/msi)?

**Comment by Tbolt10033** [comment]
> Did you install python via Microsoft Store or downloaded installer (exe/msi)?

Downloaded off of the python website and installed the exe installer.

**Comment by ApatheticDELL** [comment]
How did you install the dependencies? 
And can you run: ```pip freeze``` and paste the output? (The command pip freeze should list every module you have installed, this could be useful)

**Comment by Tbolt10033** [comment]
I installed the dependencies by doing each one with pip install module_xyz. 

Here are the installed modules:
blinker==1.8.2
certifi==2024.7.4
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comtypes==1.4.6
contourpy==1.3.1
cycler==0.12.1
discord-webhook==1.3.1
EAS2Text==0.1.12
EASGen==0.1.9
ffmpeg-python==0.2.0
Flask==3.0.3
fonttools==4.55.0
future==1.0.0
idna==3.7
itsdangerous==2.2.0
Jinja2==3.1.4
kiwisolver==1.4.7
MarkupSafe==2.1.5
matplotlib==3.9.2
numpy==2.0.1
packaging==24.2
pillow==11.0.0
PyAudio==0.2.14
pycparser==2.22
pydub==0.25.1
pyparsing==3.2.0
pypiwin32==223
python-dateutil==2.9.0.post0
pyttsx3==2.90
pywin32==306
requests==2.32.3
scipy==1.14.0
six==1.16.0
sounddevice==0.4.7
soundfile==0.12.1
urllib3==2.2.2
Werkzeug==3.0.3
xmltodict==0.13.0

**Comment by ApatheticDELL** [comment]
![{1ED5870C-DDE4-446D-9038-4DF65E002408}](https://github.com/user-attachments/assets/288e315f-b3df-4f70-ad06-ace0f3f53c43)

there we go, i finally got the error in a very fresh windows and python install

**Comment by ApatheticDELL** [comment]
So far, this seems like an issue with Matplotlib, although there is quite a problem, this is an external issue, and it's not related to QuantumENDEC...

But, I'm trying different options

- Upgrading to the latest Python 3.13.0
- Rolling back module version(?)

**Comment by ApatheticDELL** [comment]
### **I figured it out!**

To fix the _cext DLL error occurring in QuantumENDEC, you can try to install Microsoft Visual C++ Redistributable. I'm pretty sure the latest version should do well.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

We'll keep this issue open until we can confirm that this fixes it.

**Comment by BunnyTub** [comment]
The README.md file now includes the Microsoft Visual C++ Redistributable as a requirement, and includes downloads.
See pull request #12.
