### ISSUE TITLE
[Version Not Provided] PortAudio library was not found

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#13]
So when I run the QuantumENDEC, it shows that you missed the OSError of QuantumENDEC on Github Codespaces website.
![Screenshot (18)](https://github.com/user-attachments/assets/a9c5428e-6200-4479-ac32-c14538b294d6)

**Comment by meowraii** [comment]
Stop

**Comment by MidlandWR100** [comment]
i am going to eat a lithium battery please stop

**Comment by NickEASIU** [comment]
Oh okay, I'll stop that for you

**Comment by BunnyTub** [comment]
This issue cannot be fixed. You are also missing a requirement, that you must have at least 1 audio output device. Online consoles such as github.dev usually don't include support for audio.
