### ISSUE TITLE
P.S. Nothing Issues, It's working on the Web Interface on QuantumENDEC and I did it!

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#19]
Look at this picture of my screenshot!
![384731141-ad470e76-d94d-4cd7-9f79-921ae2db693d](https://github.com/user-attachments/assets/181e7b92-7748-41f9-8393-af530f7c203b)
![Screenshot (23)](https://github.com/user-attachments/assets/8fcc4e08-bd51-4e73-b981-da39c3598ee7)

**Comment by BunnyTub** [comment]
Please do not create issues if there are no issues.
Closing.

**Comment by atlantic4** [comment]
bro

**Comment by MidlandWR100** [comment]
jesus fucking christ piss offffff

**Comment by BunnyTub** [comment]
Profanity

**Comment by MidlandWR100** [comment]
> Profanity

piss off
