### ISSUE TITLE
[v5 Beta | Beta 10.3] QuantumENDEC fails to start due to missing dependencies

### ISSUE THREAD

**Issue by NickEASIU** [ApatheticDELL/QuantumENDEC#5]
**Describe the bug**
What's the bug? Try to explain as much as possible so we can have as much information about it.

**Expected behavior**

**Unexpected behavior**
Steps to reproduce the problem:

**Screenshots**

**Operating system**
 - OS: [e.g. Windows, Linux, TempleOS]
 - Python version: [e.g. v3.11, v3.12]

**Additional context**

That Problem is the code with a ImportError:

from ._cext import (
ImportError: DLL load failed while importing _cext: The specified module could not be found.

Thanks a lot with that error, You suck!

**Comment by meowraii** [comment]
Hey man, maybe thoroughly explain the problem and your environment instead of rudely telling the developers that they suck. Maybe people would be more willing to listen to you next time.

**Comment by ApatheticDELL** [comment]
Duplicate issue / slightly rude

**Comment by BunnyTub** [comment]
This is a duplicate of #4. Only create issues if they are a separate thing.
